# If your datasets live somewhere else, change ONLY the DATA_DIR line below.
from pathlib import Path

# The folder this file is in i.e. your main project folder (datatransformation.py, features.py, model_selection.py, model_evaluation.py, and this file all live here).
PROJECT_DIR = Path(__file__).resolve().parent

# Folder holding the raw datasets, and where every generated file gets written too.
# Default: a "datasets" subfolder next to the scripts, so cloning the project onto
DATA_DIR = PROJECT_DIR / "datasets"

# Folder where model_evaluation.py saves its plots/CSVs
EVALUATION_OUTPUT_DIR = PROJECT_DIR / "evaluation_outputs"

# Raw input datasets
BASE_PATH = DATA_DIR / "base_dataset.csv"
SECONDARY_PATH = DATA_DIR / "secondary_dataset.xlsx"
COMPARISON_PATH = DATA_DIR / "comparison_dataset.jsonl"

# Files generated by datatransformation.py
COMBINED_CLEAN_PATH = DATA_DIR / "combined_clean.csv"
TRAIN_PATH = DATA_DIR / "train.csv"
TEST_PATH = DATA_DIR / "test.csv"

# Trained model, generated by model_selection.py
MODEL_PATH = DATA_DIR / "ai_detector.joblib"

# make sure the folders exist no matter which script runs first
DATA_DIR.mkdir(parents=True, exist_ok=True)
EVALUATION_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)